-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Windows\Documents\Practicas MATLAB\Cuadratico\cuadratico\cuadratico_pkg.vhd
-- Created: 2022-05-28 20:58:20
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE cuadratico_pkg IS
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
END cuadratico_pkg;

